# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gomod
    directory: "/cmd/starship"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
  - package-ecosystem: gomod
    directory: "/exposer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
  - package-ecosystem: gomod
    directory: "/faucet"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
  - package-ecosystem: gomod
    directory: "/registry"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
  - package-ecosystem: gomod
    directory: "/tests/e2e"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - gh-action-version
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - docs-dependencies
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - docker-deps
