# Default values for devnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: anmol1696
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

exposer:
  image: anmol1696/exposer:latest
  port: 8081

# Chain timeouts
timeouts:
  timeout_propose: 400ms
  timeout_propose_delta: 400ms
  timeout_prevote: 400ms
  timeout_prevote_delta: 400ms
  timeout_precommit: 400ms
  timeout_precommit_delta: 400ms
  timeout_commit: 800ms

# API for interacting with the charts for devnet
# TODO: need a way to create state reaching jobs, those will run user bash scripts
# after the chain has been initialized, get the chain to a state and then complete
chains:
  osmosis:
    name: osmosis
    image: anmol1696/osmosis:latest
    home: /root/.osmosisd
    binary: osmosisd
    prefix: osmo
    denom: uosmo
    coins: 100000000000000uosmo,100000000000000uion
    numValidators: 2
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    wasm:
      enabled: true
      permissionless: true
    localPorts:
      rpc: 26653
      rest: 1313
  wasmd:
    name: wasmd
    image: anmol1696/wasmd:latest
    home: /root/.wasmd
    binary: wasmd
    prefix: wasm
    denom: stake
    coins: 100000000000000ucosm,100000000000000stake
    numValidators: 2
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    wasm:
      enabled: true
      permissionless: true
    localPorts:
      rpc: 26659
      rest: 1319

# TODO: ability to check the srcConnection and destConnection to use
relayers:
  rly1:
    name: osmo-wasm
    kind: ts-relayer
    image: anmol1696/ts-relayer:latest
    replicas: 1 # these are unique replicas, currently only support a single replica
    chains:
      - osmosis
      - wasmd

explorer:
  enabled: true # Flag to enable disable explorer
  type: ping-pub
  image: anmol1696/explorer
  localhost: true
  localPorts:
    rest: 8080

faucet:
  enabled: false # will create faucet for all chains
