# Default values for devnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  init:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "1"
      memory: "1Gi"
  wait:
    limits:
      cpu: "0.1"
      memory: "100M"
    requests:
      cpu: "0.1"
      memory: "100M"

exposer:
  image: anmol1696/exposer:20230319-e41e51f
  ports:
    rest: 8081
  resources:
    limits:
      cpu: "0.2"
      memory: "200M"
    requests:
      cpu: "0.2"
      memory: "200M"

# Chain timeouts
timeouts:
  time_iota_ms: 10
  timeout_propose: 400ms
  timeout_propose_delta: 400ms
  timeout_prevote: 400ms
  timeout_prevote_delta: 400ms
  timeout_precommit: 400ms
  timeout_precommit_delta: 400ms
  timeout_commit: 800ms

# API for interacting with the charts for devnet
# TODO: need a way to create state reaching jobs, those will run user bash scripts
# after the chain has been initialized, get the chain to a state and then complete
defaultChains:
  osmosis:
    image: marcpt/osmosis:15.0.0-amd64
    home: /root/.osmosisd
    binary: osmosisd
    prefix: osmo
    denom: uosmo
    coins: 100000000000000000000uosmo,100000000000000000000uion
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/osmosis-labs/osmosis
  juno:
    image: anmol1696/juno:latest
    home: /root/.juno
    binary: junod
    prefix: juno
    denom: ujuno
    coins: 100000000000000ujuno
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/CosmosContracts/juno
  wasmd:
    image: anmol1696/wasmd:latest
    home: /root/.wasmd
    binary: wasmd
    prefix: wasm
    denom: stake
    coins: 100000000000000ucosm,100000000000000stake
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/CosmWasm/wasmd
  cosmos:
    image: mkoijn6/gaia-lsm
    home: /root/.gaia
    binary: gaiad
    prefix: cosmos
    denom: uatom
    coins: 100000000000000000000stake,100000000000000000000uatom
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/cosmos/gaia
  persistencecore:
    image: mkoijn6/pstake-lsm
    home: /root/.pstaked
    binary: pstaked
    prefix: persistence
    denom: uxprt
    coins: 100000000000000000000uxprt
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/persistenceOne/pstake-native

defaultRelayers:
  ts-relayer:
    image: anmol1696/ts-relayer:latest
  hermes:
    image: marcpt/hermes:1.5.1-amd64
  go-relayer:
    image: anmol1696/go-relayer:latest
  icq:
    image: marcpt/persistenceone-icq:latest-amd64

chains:
#  Examples running chains
   - name: gaia-1
     type: cosmos
     numValidators: 4
     ports:
       rpc: 26653
       rest: 1313
     resources:
       limits:
         cpu: "1"
         memory: "1Gi"
       requests:
         cpu: "1"
         memory: "1Gi"
   - name: osmosis-1
     type: osmosis
     numValidators: 4
     ports:
       rpc: 26654
       rest: 1314
     resources:
       limits:
         cpu: "1"
         memory: "1Gi"
       requests:
         cpu: "1"
         memory: "1Gi"
   - name: core-1
     type: persistencecore
     numValidators: 1
     ports:
       rpc: 26657
       rest: 1317
     resources:
       limits:
         cpu: "1"
         memory: "1Gi"
       requests:
         cpu: "1"
         memory: "1Gi"

# TODO: ability to check the srcConnection and destConnection to use
relayers:
# Example relayers, default is set to none
  - name: persistence-cosmos
    type: icq
    replicas: 1 # these are unique replicas, currently only support a single replica
    chains:
      - core-1
      - gaia-1
  - name: persistence-cosmos
    type: hermes
    replicas: 1 # these are unique replicas, currently only support a single replica
    chains:
      - gaia-1
      - core-1
  - name: persistence-osmosis
    type: icq
    replicas: 1 # these are unique replicas, currently only support a single replica
    chains:
      - core-1
      - osmosis-1
  - name: persistence-osmosis
    type: hermes
    replicas: 1 # these are unique replicas, currently only support a single replica
    chains:
      - osmosis-1
      - core-1

explorer:
  # Flag to enable explorer for cluster
  enabled: false
  type: ping-pub
  image: anmol1696/explorer
  localhost: true
  ports:
    rest: 8080
  resources:
    limits:
      cpu: "0.5"
      memory: "500M"
    requests:
      cpu: "0.5"
      memory: "500M"


faucet:
  enabled: false

registry:
  enabled: false
  image: anmol1696/registry
  ports:
    rest: 6060
    grpc: 7070
  resources:
    limits:
      cpu: "0.2"
      memory: "200M"
    requests:
      cpu: "0.2"
      memory: "200M"

collector:
  enabled: false
  image: anmol1696/collector:latest
  localhost: true
  ports:
    rest: 8070
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "0.5"
      memory: 1Gi
