chains:
  - id: injective-1
    name: injective
    numValidators: 1
    resources:
      cpu: "0.2"
      memory: "200M"
    faucet:
      type: starship
      concurrency: 2
      resources:
        cpu: "0.2"
        memory: "200M"
    ports:
      rest: 1313
      rpc: 26653
      exposer: 38083
      faucet: 8003
  - id: cosmoshub-4
    name: cosmoshub
    numValidators: 1
    resources:
      cpu: "0.2"
      memory: "200M"
    faucet:
      type: cosmjs
      concurrency: 2
      resources:
        cpu: "0.2"
        memory: "200M"
    ports:
      rest: 1317
      rpc: 26657
      exposer: 38087
      faucet: 8007

relayers:
  - name: injective-cosmos
    type: hermes
    replicas: 1
    chains:
      - injective-1
      - cosmoshub-4
    resources:
      cpu: "0.2"
      memory: "200M"

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091
  resources:
    cpu: "0.1"
    memory: "100M"

