chains:
  - name: neutron-1
    type: neutron
    numValidators: 1
    faucet:
      enabled: false
    ics:
      enabled: true
    ports:
      rest: 1313
      rpc: 26653
      exposer: 38083
    resources:
      cpu: "0.2"
      memory: "200M"
  - name: cosmoshub-4
    type: cosmos
    numValidators: 1
    faucet:
      type: cosmjs
      concurrency: 2
      resources:
        cpu: "0.2"
        memory: "200M"
    ports:
      rest: 1317
      rpc: 26657
      exposer: 38087
      faucet: 8007
    resources:
      cpu: "0.2"
      memory: "200M"

relayers:
  - name: neutron-cosmos
    type: hermes
    replicas: 1
    chains:
      - neutron-1
      - cosmoshub-4
    resources:
      cpu: "0.2"
      memory: "200M"

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091
  resources:
    cpu: "0.1"
    memory: "100M"

