chains:
  - id: osmosis-1
    name: osmosis
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
  - id: wasmd
    name: wasmd
    numValidators: 1
    ports:
      rpc: 26659
      rest: 1319
