chains:
  - id: neutron-1
    name: neutron
    numValidators: 1
    faucet:
      enabled: false
    ports:
      rest: 1313
      rpc: 26653
      exposer: 38083
  - id: cosmoshub-4
    name: cosmoshub
    numValidators: 4
    ports:
      rest: 1317
      rpc: 26657
      exposer: 38087
      faucet: 8007

relayers:
  - name: neutron-cosmos
    type: hermes
    replicas: 1
    chains:
      - neutron-1
      - cosmoshub-4

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091

