{{- $keys := .Files.Get "configs/keys.json" | fromJson }}
{{- range $relayer := .Values.relayers }}
{{- if eq $relayer.type "go-relayer" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $relayer.type }}-{{ $relayer.name }}"
data:
  path.json: |-
    {
      "src": {
        "chain-id": "{{ index $relayer.chains 0 }}"
      },
      "dst": {
        "chain-id": "{{ index $relayer.chains 1 }}"
      },
      "src-channel-filter": {
        "rule": null,
        "channel-list": []
      }
    }
  {{ $defaultFile := $.Files.Get "defaults.yaml" | fromYaml }}
  {{- range $i, $chain := $relayer.chains }}
  {{ $fullchain := include "devnet.fullchain" (dict "name" $chain "file" $defaultFile "context" $) | fromJson }}
  {{ $fullchain.name }}.json: |-
    {
      "type": "cosmos",
      "value": {
        "key": "default",
        "chain-id": "{{ $fullchain.name }}",
        {{- if $fullchain.cometmock.enabled }}
        "rpc-addr": "http://{{ $fullchain.hostname }}-cometmock.{{ $.Release.Namespace }}.svc.cluster.local:22331",
        {{- else}}
        "rpc-addr": "http://{{ $fullchain.hostname }}-genesis.{{ $.Release.Namespace }}.svc.cluster.local:26657",
        {{- end }}
        "account-prefix": "{{ $fullchain.prefix }}",
        "keyring-backend": "test",
        "gas-adjustment": 20,
        "gas-prices": "0.25{{ $fullchain.denom }}",
        "min-gas-amount": 100000000000,
        "debug": true,
        "timeout": "20s",
        "output-format": "json",
        "sign-mode": "direct"
      }
    }
  {{- end }}
---
{{- end }}
{{- end }}
