{{- range $chain := .Values.chains }}
{{- if ne $chain.type "virtual" }}
{{- if ($chain.cometMock.enabled) }}
{{ $dataExposer := dict "chain" $chain.name "port" ($.Values.exposer.ports.rest | quote | default "8081") }}
{{ $defaultFile := $.Files.Get "defaults.yaml" | fromYaml }}
{{ $defaultChain := get $defaultFile.defaultChains $chain.type | default dict }}

# merge defaultChain values into the $chain dict
{{ $chain = merge $chain $defaultChain }}

# read faucet from chain values and merge with default faucet values
{{ $faucet := get $chain "faucet" | default dict }}
{{ $faucet = mergeOverwrite ($.Values.faucet | deepCopy) $faucet }}

{{ $defaultFaucet := get $defaultFile.defaultFaucet $faucet.type | default dict }}
{{ $faucet = merge $faucet $defaultFaucet }}

{{ $image := $chain.cometMock.image | default $defaultFile.defaultCometMock.image }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devnet.chain.name" $chain.name }}-comet-mock
  labels:
    app.kubernetes.io/name: {{ $chain.name }}-comet-mock
spec:
  clusterIP: None
  ports:
    - name: rpc
      port: 22331
      protocol: TCP
      targetPort: 22331
  selector:
    app.kubernetes.io/name: {{ $chain.name }}-comet-mock
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "devnet.chain.name" $chain.name }}-comet-mock
spec:
  serviceName: {{ include "devnet.chain.name" $chain.name }}-comet-mock
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $chain.type }}
      app.kubernetes.io/name: {{ $chain.name }}-comet-mock
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: {{ $chain.type }}
        app.kubernetes.io/type: comet-mock
        app.kubernetes.io/name: {{ $chain.name }}-comet-mock
        app.kubernetes.io/rawname: {{ $chain.name }}-comet-mock
        app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    spec:
      {{- include "imagePullSecrets" $chain | indent 6 }}
      initContainers:
        - name: init-node
          image: {{ $image }}
          imagePullPolicy: Always
          env:
            {{- include "devnet.defaultEvnVars" $chain | indent 12 }}
            {{- include "devnet.evnVars" $chain | indent 12 }}
            {{- include "devnet.genesisVars" $dataExposer | indent 12 }}
            {{- include "devnet.timeoutVars" $.Values | indent 12 }}
          command:
            - bash
            - "-c"
            - |
              mkdir -p /chain/genesis
              curl http://$GENESIS_HOST.$NAMESPACE.svc.cluster.local:$GENESIS_PORT/genesis -o /chain/genesis/config/genesis.json
              echo "Genesis file that we got....."
              cat /chain/genesis/config/genesis.json

              ## fetch priv_validator and priv_validator_state of all validators
              mkdir -p /chain/genesis/config /chain/genesis/data
              curl http://$GENESIS_HOST.$NAMESPACE.svc.cluster.local:$GENESIS_PORT/priv_keys -o /chain/genesis/config/priv_validator_key.json
              curl http://$GENESIS_HOST.$NAMESPACE.svc.cluster.local:$GENESIS_PORT/priv_validator_state -o /chain/genesis/data/priv_validator_state.json

              {{- if gt $chain.numValidators 1.0}}
              for i in $(seq 0 {{ sub $chain.numValidators 2 }});
              do
                mkdir -p /chain/validator-$i/config /chain/validator-$i/data
                curl http://{{ include "devnet.chain.name" .chain }}-validator-$i.$NAMESPACE.svc.cluster.local:$GENESIS_PORT/priv_keys -o /chain/validator-$i/config/priv_validator_key.json
                curl http://{{ include "devnet.chain.name" .chain }}-validator-$i.$NAMESPACE.svc.cluster.local:$GENESIS_PORT/priv_validator_state -o /chain/validator-$i/data/priv_validator_state.json
              done
              {{- end }}
          resources: {{- include "devnet.node.resources" ( dict "node" $chain "context" $ ) | trim | nindent 12 }}
          volumeMounts:
            - mountPath: /chain
              name: node
            - mountPath: /scripts
              name: scripts
      containers:
        - name: comet
          image: {{ $image }}
          imagePullPolicy: Always
          env:
            {{- include "devnet.defaultEvnVars" $chain | indent 12 }}
            {{- include "devnet.evnVars" $chain | indent 12 }}
            {{- include "devnet.genesisVars" $dataExposer | indent 12 }}
          command:
            - bash
            - "-c"
            - |
              NODE_LISTEN_ADDR_STR="tcp://{{ include "devnet.chain.name" .chain }}-genesis.$NAMESPACE.svc.cluster.local:26658"
              NODE_HOME_STR="/chain/genesis"

              {{- if gt $chain.numValidators 1.0}}
              for i in $(seq 0 {{ sub $chain.numValidators 2 }});
              do
                NODE_LISTEN_ADDR_STR="http://{{ include "devnet.chain.name" .chain }}-validator-$i.$NAMESPACE.svc.cluster.local:26658,$NODE_LISTEN_ADDR_STR"
                NODE_HOME_STR="/chain/validator-$i,$NODE_HOME_STR"
              done
              {{- end }}
              sleep 1000000000
              cometmock $NODE_LISTEN_ADDR_STR /chain/genesis/config/genesis.json tcp://0.0.0.0:22331 $NODE_HOME_STR grpc --block-time={{ $.Values.timeouts.timeout_commit | replace "ms" "" }}
          resources: {{- include "devnet.node.resources" ( dict "node" $chain "context" $ ) | trim | nindent 12 }}
          volumeMounts:
            - mountPath: /chain
              name: node
            - mountPath: /scripts
              name: scripts
      volumes:
        - name: node
          emptyDir: { }
        - name: scripts
          configMap:
            name: setup-scripts-{{- include "devnet.chain.name" $chain.name }}
---
{{- end }}
{{- end }}
{{- end }}
