# Example values.yaml file will create 2 chains with 4 validators,
# a ts-relayer between them and the explorer
chains:
  - name: osmosis-1
    type: osmosis
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
  - name: juno-1
    type: juno
    numValidators: 1
    ports:
      rest: 1315
      rpc: 26655
  - name: cosmoshub-1
    type: cosmos
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657

relayers:
  - name: osmos-juno
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - core-1
  - name: osmos-cosmos
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - cosmoshub-1

explorer:
  enabled: true
  ports:
    rest: 8080

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091
