chains:
  - name: simapp
    type: simapp
    numValidators: 20
    ports:
      rest: 1317
      rpc: 26657

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: true
  ports:
    rest: 8080
