chains:
  - name: simapp
    type: simapp
    numValidators: 50
    ports:
      rest: 1317
      rpc: 26657
    resources:
      limits:
        cpu: "0.3"
        memory: "1Gi"
      requests:
        cpu: "0.3"
        memory: "1Gi"

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: true
  ports:
    rest: 8080

exposer:
  resources:
    limits:
      cpu: "0.1"
      memory: "100M"
    requests:
      cpu: "0.1"
      memory: "100M"
