chains:
  - name: simapp
    type: simapp
    numValidators: 2
    ports:
      rest: 1317
      rpc: 26657
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "1"
        memory: "2Gi"

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: true
  ports:
    rest: 8080
