chains:
  - name: simapp
    type: simapp
    image: ghcr.io/cosmos/simapp:latest
    numValidators: 2
    ports:
      rest: 1317
      rpc: 26657
      grpc: 9091
      faucet: 8001
    faucet:
      # use v0.31.0-alpha.2 cosmjs-faucet for compatibility with simapp v0.47.3
      image: ghcr.io/cosmology-tech/starship/cosmjs-faucet:v0.31.0
      concurrency: 4

exposer:
  image: ghcr.io/cosmology-tech/starship/exposer:20230808-2333929

registry:
  enabled: true
  ports:
    rest: 8081

explorer:
  enabled: true
  ports:
    rest: 8080
