chains:
  - name: simapp
    type: cosmos
    numValidators: 1
    image: ghcr.io/cosmology-tech/starship/simapp:v0.47.3
    home: /root/.simd
    binary: simd

registry:
  enabled: true

explorer:
  enabled: true
