{{ $portMap := dict "p2p" 26656 "rpc" 26657 "grpc" 9090 "rest" 1317 }}
{{- range $chain := .Values.chains }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $chain.name }}-genesis
  annotations:
    {{- if eq $.Values.service.type "LoadBalancer" }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- end }}
    {{- if eq $chain.name "consumer" }}
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-024965f9be1f81ba4
    {{- else if eq $chain.name "provider" }}
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0474d55d551e65f3e
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ $chain.name }}-genesis
spec:
  {{- if eq $.Values.service.type "ClusterIP" }}
  clusterIP: None
  {{- end }}
  type: {{ $.Values.service.type }}
  ports:
    {{- range $name, $port := $portMap }}
    - name: {{ $name }}
      port: {{ $port }}
      protocol: TCP
      targetPort: {{ $port }}
    {{- end }}
    - name: http
      port: {{ $.Values.exposer.ports.rest | default 8081 }}
      protocol: TCP
      targetPort: {{ $.Values.exposer.ports.rest | default 8081 }}
    - name: faucet
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: {{ $chain.name }}-genesis
---
{{- end }}
