name: Build

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build-exposer:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true

      - name: Build exposer
        run: |
          cd exposer && make build

  build-registry:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true

      - name: Build registry
        run: |
          cd registry && make build

  build-faucet:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true

      - name: Build faucet
        run: |
          cd faucet && make build
