name: All Docker

on:
  push:
    paths:
      - 'docker/**/*'
    branches:
      - main
  pull_request:
    paths:
      - 'docker/**/*'
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build docker images
        run: |
          changed_dirs=$(git diff --name-only --diff-filter=d origin/main...HEAD | grep '^docker/.*\/.*$' | awk -F '/' '{print $2"/"$3}' | sort | uniq)
          echo "$changed_dirs" | while read -r changed_dir; do
            type=$(echo "$changed_dir" | awk -F '/' '{print $1}')
            process=$(echo "$changed_dir" | awk -F '/' '{print $2}')
            if [ ${{ github.ref }} == 'refs/heads/main' ]; then
              ./scripts/build-docker.sh -t "$type" -p "$process" --push --push-latest
            else
              ./scripts/build-docker.sh -t "$type" -p "$process"
            fi
          done
