name: Deploy images to GHCR

on:
  push:
    branches:
      - main
      - anmol/docker-chains-expansion
    paths:
      - "docker/**"
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    # subdirs of docker/ directory to build
    strategy:
      matrix:
        build-type: [ "chains", "explorers", "faucet", "relayers", "starship" ]
      max-parallel: 2

    env:
      DOCKER_REPO: ghcr.io/cosmology-tech/starship

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all chains
        if: matrix.build-type == "chains"
        run: |
          ./docker/chains/build-docker.sh --chain all --tag all --push

      - name: Build all build types
        if: matrix.build-type != "chains"
        run: |
          ./scripts/build-docker.sh --type ${{ matrix.build-type }} --process all --version all --push
