name: Docs

on:
  push:
    branches:
      - main
      - anmol/automated-docs-pipeline  # debug branch: todo: remove before merge
    paths:
      - "docs/**"
      - ".github/workflows/docs.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone docs repository
        run: git clone https://x-access-token:${{ secrets.GH_PAT_TOKEN }}@github.com/cosmology-tech/docs.git external-docs

      - name: Sync the docs
        run: |
          rsync -av --delete ./docs/pages/ ./external-docs/pages/starship/
          cd external-docs
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add .
          git commit -m "Aotumated: Update starship documentation from starship repo"
          if git diff --quiet; then
              echo "No changes to commit."
          else
              git push