name: mkdocs

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/docs.yaml
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      runs-on: ubuntu-latest
      steps:
        - name: checkout 🛎️
          uses: actions/checkout@v2.3.1
        - name: node
          uses: actions/setup-node@v3
          with:
            node-version: 18.4.0
        - name: deps
          run: yarn
        - name: bootstrap
          run: yarn bootstrap
        - name: build
          run: yarn build
        - name: deploy
          run: yarn deploy:all
