name: E2E tests

on:
  push:
    branches:
      - main
  # Run every day at 18:00 UTC
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: {}

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}

    strategy:
      matrix:
        config-file: [ "one-chain.yaml", "two-chain.yaml", "build-chain.yaml" ]
      fail-fast: true
      max-parallel: 1

    env:
      CONFIG_FILE: "tests/configs/${{ matrix.config-file }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run remote e2e test
        uses: ./.github/actions/e2e-test
        with:
          config-file: ${{ env.CONFIG_FILE }}
