name: mkdocs

on:
  push:
    branches:
      - master
      - anmol/docs
    paths:
      - docs/**
      - .github/workflows/mkdocs.yaml

jobs:
  deploy:
    runs-on: shared-runner

    container:
      image: docker.io/squidfunk/mkdocs-material

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy mkdocs to GitHub Pages
        run: |
          cd docs
          mkdocs gh-deploy --force
