name: PR tests

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-pr-tests
  cancel-in-progress: true

jobs:
  pr-test:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        config-file:
          - "one-chain-custom-scripts.yaml"
          - "one-chain.yaml"
          - "one-custom-chain.yaml"
          - "multi-validator.yaml"
          - "simapp.yaml"
          - "one-chain-starship-faucet.yaml"
          - "multi-validator-starship-faucet.yaml"
          - "one-chain-cometmock.yaml"
      fail-fast: true
      max-parallel: 3

    env:
      CONFIG_FILE: "tests/e2e/configs/${{ matrix.config-file }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true

      - name: Setup Test infra
        id: starship-action
        uses: cosmology-tech/starship-action@40850df7d3346bdeafc4bb95c0778bbef191e030
        with:
          values: ${{ env.CONFIG_FILE }}
          port-forward: true
          version: 0.0.0
          chart: ./charts/devnet
          cli-version: 42031163298cc2ef648cd7d01eb16be92f91f97d

      - name: Run tests
        run: |
          cd tests/e2e/ && go test -v ./...
        env:
          TEST_CONFIG_FILE: ${{ env.CONFIG_FILE }}

      # todo: change this to be post step of the action
      - name: Cleanup cluster
        if: always()
        run: |
          helm delete $DEVNET_NAME --debug --namespace $DEVNET_NAMESPACE --wait || true
          kubectl delete namespace $DEVNET_NAMESPACE --wait=true || true
        env:
          DEVNET_NAME: ${{ steps.starship-action.outputs.name }}
          DEVNET_NAMESPACE: ${{ steps.starship-action.outputs.namespace }}
