name: Smoke tests

on:
  # Run every day at 20:00 UTC
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-smoke-tests
  cancel-in-progress: true

jobs:
  smoke-test-1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config-file: [ "one-chain.yaml", "osmojs.yaml", "simapp.yaml", "multi-validator.yaml" ]
      fail-fast: false
      max-parallel: 4

    env:
      CONFIG_FILE: "tests/smoke/ci/${{ matrix.config-file }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Test infra
        id: starship-action
        uses: cosmology-tech/starship-action@0.2.19
        with:
          values: ${{ env.CONFIG_FILE }}
          port-forward: true
          version: 0.0.0
          chart: ./charts/devnet
          timeout: 10m
          cli-version: f35dc85407b350077765a0b3c17a4c1632c7d53c

      # todo: change this to be post step of the action
      - name: Cleanup cluster
        if: always()
        run: |
          helm delete $DEVNET_NAME --debug --namespace $DEVNET_NAMESPACE --wait || true
          kubectl delete namespace $DEVNET_NAMESPACE --wait=true || true
        env:
          DEVNET_NAME: ${{ steps.starship-action.outputs.name }}
          DEVNET_NAMESPACE: ${{ steps.starship-action.outputs.namespace }}

  smoke-test-2:
    needs: [smoke-test-1]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config-file: [ "one-chain.yaml", "osmojs.yaml", "simapp.yaml", "multi-validator.yaml" ]
      fail-fast: true
      max-parallel: 4

    env:
      CONFIG_FILE: "tests/smoke/ci/${{ matrix.config-file }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Test infra
        id: starship-action
        uses: cosmology-tech/starship-action@0.2.19
        with:
          values: ${{ env.CONFIG_FILE }}
          port-forward: true
          version: 0.0.0
          chart: ./charts/devnet
          timeout: 10m
          cli-version: f35dc85407b350077765a0b3c17a4c1632c7d53c

      # todo: change this to be post step of the action
      - name: Cleanup cluster
        if: always()
        run: |
          helm delete $DEVNET_NAME --debug --namespace $DEVNET_NAMESPACE --wait || true
          kubectl delete namespace $DEVNET_NAMESPACE --wait=true || true
        env:
          DEVNET_NAME: ${{ steps.starship-action.outputs.name }}
          DEVNET_NAMESPACE: ${{ steps.starship-action.outputs.namespace }}

  smoke-test-3:
    needs: [smoke-test-2]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config-file: [ "one-chain.yaml", "osmojs.yaml", "simapp.yaml", "multi-validator.yaml" ]
      fail-fast: true
      max-parallel: 4

    env:
      CONFIG_FILE: "tests/smoke/ci/${{ matrix.config-file }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Test infra
        id: starship-action
        uses: cosmology-tech/starship-action@0.2.19
        with:
          values: ${{ env.CONFIG_FILE }}
          port-forward: true
          version: 0.0.0
          chart: ./charts/devnet
          timeout: 10m
          cli-version: f35dc85407b350077765a0b3c17a4c1632c7d53c

      # todo: change this to be post step of the action
      - name: Cleanup cluster
        if: always()
        run: |
          helm delete $DEVNET_NAME --debug --namespace $DEVNET_NAMESPACE --wait || true
          kubectl delete namespace $DEVNET_NAMESPACE --wait=true || true
        env:
          DEVNET_NAME: ${{ steps.starship-action.outputs.name }}
          DEVNET_NAMESPACE: ${{ steps.starship-action.outputs.namespace }}
