name: Starship Docker

on:
  push:
    branches:
      - main

jobs:
  deploy-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v3
        env:
          version: 4.2.1
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-${{ env.version }}-bazel-cache

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Determine tag
        id: docker-tag
        run: |
          tag=$(date -u "+%Y%m%d")-$(echo ${GITHUB_SHA} | cut -c1-7)
          echo Tag will be $tag
          echo ::set-output name=version::$tag

      - name: Build and push docker image for registry
        run: bazel run --define=DOCKER_TAG_NAME=${{ env.DOCKER_TAG_NAME }} //registry:image_push
        env:
          DOCKER_TAG_NAME: ${{ steps.docker-tag.outputs.version }}

      - name: Build and push docker image for registry
        run: bazel run --define=DOCKER_TAG_NAME=${{ env.DOCKER_TAG_NAME }} //exposer:image_push
        env:
          DOCKER_TAG_NAME: ${{ steps.docker-tag.outputs.version }}
