name: Starship Docker

on:
  push:
    branches:
      - main
  # debug
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-starship-docker
  cancel-in-progress: true

jobs:
  deploy-docker:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    env:
      DOCKER_REPO: ghcr.io/cosmology-tech/starship

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tag
        id: docker-tag
        run: |
          tag=$(date -u "+%Y%m%d")-$(echo ${GITHUB_SHA} | cut -c1-7)
          echo Tag will be $tag
          echo ::set-output name=version::$tag

      - name: Build and push docker image for registry
        uses: docker/build-push-action@v4
        with:
          push: true
          context: registry/
          tags: ghcr.io/cosmology-tech/starship/registry:${{ steps.docker-tag.outputs.version }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push docker image for exposer
        uses: docker/build-push-action@v4
        with:
          push: true
          context: exposer/
          tags: ghcr.io/cosmology-tech/starship/exposer:${{ steps.docker-tag.outputs.version }}
          platforms: linux/amd64,linux/arm64
