name: Temp Docker

on:
  push:
    branches:
      - anmol/remote-exec-commands
    paths:
      - "docker/**"
      - ".github/workflows/docker.yaml"

jobs:
  build-push-hermes:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    env:
      DOCKER_REPO: ghcr.io/cosmology-tech/starship

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 -t ${{ env.DOCKER_REPO }}/hermes:39033cdee9e7aaa2274aeca3ab152542bf93d8bd -f docker/relayers/hermes/Dockerfile.native . --push

